repos:
  # 🔑 Gitleaks - secret scanning (all file types)
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # 📦 Config file validity + large file prevention
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=512"]

  # 🧹 Formatting / safety extras
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.35.0
    hooks:
      - id: eslint
        additional_dependencies: ["eslint@9.4.0"]
